title: "DeFi & Crypto Conference"
description: "26-28 January 2026 â€” Scuola Normale Superiore, Pisa."
url: "https://sns-defi.github.io"
baseurl: "" # set to /repo-name if using a project site
markdown: kramdown
theme: null
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
permalink: pretty
timezone: Europe/Rome
author:
  name: "Organizing Committee"
